# Generated by Django 5.1.7 on 2025-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="token",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
