# Generated by Django 5.1.7 on 2025-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("model_no", models.CharField(max_length=50)),
                ("stok_kodu", models.CharField(max_length=50, unique=True)),
                (
                    "qr_kod",
                    models.ImageField(blank=True, null=True, upload_to="qr_kodlari/"),
                ),
            ],
        ),
    ]
