# Generated by Django 5.1.7 on 2025-08-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urun", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="adet",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="urun",
            name="durum",
            field=models.CharField(
                choices=[
                    ("stokta", "Stokta"),
                    ("satildi", "Satıldı"),
                    ("incelemede", "İncelemede"),
                    ("hasarli", "Hasarlı"),
                    ("iade", "İade"),
                    ("rezerve", "Rezerve"),
                    ("silindi", "Silindi"),
                ],
                default="stokta",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="UrunDurumGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onceki_durum",
                    models.CharField(
                        choices=[
                            ("stokta", "Stokta"),
                            ("satildi", "Satıldı"),
                            ("incelemede", "İncelemede"),
                            ("hasarli", "Hasarlı"),
                            ("iade", "İade"),
                            ("rezerve", "Rezerve"),
                            ("silindi", "Silindi"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "yeni_durum",
                    models.CharField(
                        choices=[
                            ("stokta", "Stokta"),
                            ("satildi", "Satıldı"),
                            ("incelemede", "İncelemede"),
                            ("hasarli", "Hasarlı"),
                            ("iade", "İade"),
                            ("rezerve", "Rezerve"),
                            ("silindi", "Silindi"),
                        ],
                        max_length=15,
                    ),
                ),
                ("aciklama", models.TextField(blank=True)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durum_gecmisi",
                        to="urun.urun",
                    ),
                ),
                (
                    "yapan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
