# Generated by Django 5.1.7 on 2025-08-05 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("urun", "0002_urun_adet_urun_durum_urundurumgecmisi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urun",
            name="adet",
        ),
    ]
