# Generated by Django 5.1.7 on 2025-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urun", "0003_remove_urun_adet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urundurumgecmisi",
            name="onceki_durum",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stokta", "Stokta"),
                    ("satildi", "Satıldı"),
                    ("incelemede", "İncelemede"),
                    ("hasarli", "Hasarlı"),
                    ("iade", "İade"),
                    ("rezerve", "Rezerve"),
                    ("silindi", "Silindi"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
